@baseUrl = http://10.0.0.91:8080/api
### ON1
GET {{baseUrl}}/on?level=1
Content-Type: application/json

### ON2
GET {{baseUrl}}/on?level=2
Content-Type: application/json

### ON3
GET {{baseUrl}}/on?level=3
Content-Type: application/json


### OFF
GET {{baseUrl}}/off
Content-Type: application/json


### status 
GET {{baseUrl}}/status
Content-Type: application/json


### timer
GET {{baseUrl}}/timer_off?seconds=5
Content-Type: application/json


### canel timer
GET {{baseUrl}}/cancel_timer
Content-Type: application/json  

